export const FETCH_100_POSTS = "FETCH_100_POSTS";
export const FETCH_10_USER = "FETCH_10_USER";

export const FETCH_10_USER_SUCCESSFULL = "FETCH_10_USER_SUCCESSFULL";
export const FETCH_200_TODOS = "FETCH_200_TODOS";
